name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # safety net in case requirements.txt misses them
          pip install pytest pytest-cov

      - name: Run tests with coverage (fail if < 90%)
        run: |
          pytest --cov=app --cov-report=term-missing --cov-fail-under=90

      - name: Upload coverage report artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: |
            .coverage
            htmlcov/
          if-no-files-found: ignore